# Numpy

In [2]:
# this is Numerical Python 
# it provides us with functionality such as 

# numpy arrays 
# matrix like representations 
# random number generation 

In [3]:
# installation 
# pip install numpy / conda install numpy 

In [4]:
import numpy 

In [6]:
print(dir(numpy))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

### basic usage

In [8]:
list1 = [1,2,3,4,5,6]

arr = numpy.array(list1)

In [9]:
print(list1)

[1, 2, 3, 4, 5, 6]


In [10]:
print(arr)

[1 2 3 4 5 6]


In [11]:
print(type(list1), type(arr))

<class 'list'> <class 'numpy.ndarray'>


In [13]:
arr[-1]

6

#### speed of numpy arrays 

In [18]:
from timeit import Timer # timer

Nelements = 10000
Ntimeits = 10000

x = numpy.arange(Nelements)
y = range(Nelements)

print(x)
print('*'*35)
print(y)

[   0    1    2 ... 9997 9998 9999]
***********************************
range(0, 10000)


In [21]:
# Do a sum over the list and the numpy array 

t_numpy = Timer("x.sum()","from __main__ import x")
t_list = Timer("sum(y)","from __main__ import y")

print("numpy: %.3e" % (t_numpy.timeit(Ntimeits)/Ntimeits))
print("list: %.3e" % (t_list.timeit(Ntimeits)/Ntimeits))

numpy: 1.184e-05
list: 2.364e-04


In [22]:
x.sum()

49995000

In [24]:
sum(y)

49995000

### Numpy Dimensions

#### 0-D Array

In [25]:
age = 45

arr0d = numpy.array(age)

print(arr0d, type(arr0d))

45 <class 'numpy.ndarray'>


### 1-D Array

In [26]:
arr1d = numpy.array(list1)

print(arr1d, type(arr1d))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


### 2-D Array

In [28]:
list2 = [[1,2,3,4],[5,6,7,8]]

arr2d = numpy.array(list2)

print(arr2d, type(arr2d), arr2d.shape)

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> (2, 4)


In [30]:
# use numpy.arange to create a range 
# of numbers

nos = numpy.arange(10)

print(nos, type(nos))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [34]:
# optional args for the starting point 
# and step size

nos = numpy.arange(0,20,2)

print(nos, type(nos))

[ 0  2  4  6  8 10 12 14 16 18] <class 'numpy.ndarray'>


In [36]:
# is this array 1-D or 2-D ?

numpy.linspace(1,11,100)

array([ 1.        ,  1.1010101 ,  1.2020202 ,  1.3030303 ,  1.4040404 ,
        1.50505051,  1.60606061,  1.70707071,  1.80808081,  1.90909091,
        2.01010101,  2.11111111,  2.21212121,  2.31313131,  2.41414141,
        2.51515152,  2.61616162,  2.71717172,  2.81818182,  2.91919192,
        3.02020202,  3.12121212,  3.22222222,  3.32323232,  3.42424242,
        3.52525253,  3.62626263,  3.72727273,  3.82828283,  3.92929293,
        4.03030303,  4.13131313,  4.23232323,  4.33333333,  4.43434343,
        4.53535354,  4.63636364,  4.73737374,  4.83838384,  4.93939394,
        5.04040404,  5.14141414,  5.24242424,  5.34343434,  5.44444444,
        5.54545455,  5.64646465,  5.74747475,  5.84848485,  5.94949495,
        6.05050505,  6.15151515,  6.25252525,  6.35353535,  6.45454545,
        6.55555556,  6.65656566,  6.75757576,  6.85858586,  6.95959596,
        7.06060606,  7.16161616,  7.26262626,  7.36363636,  7.46464646,
        7.56565657,  7.66666667,  7.76767677,  7.86868687,  7.96

### Arithmetic operations on numpy array

In [37]:
import numpy as np 

arr = np.arange(0,11)
arr2 = np.arange(0,21,2)

In [38]:
print(arr,'\n',arr2)

[ 0  1  2  3  4  5  6  7  8  9 10] 
 [ 0  2  4  6  8 10 12 14 16 18 20]


In [39]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
print(arr / 2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [41]:
arr2 > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [42]:
arr + arr2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [43]:
print(arr.size, arr2.size)

11 11


In [44]:
arr3 = np.array([[2,4,6,8],[1,2,3,4]])

In [45]:
arr2 + arr3

ValueError: operands could not be broadcast together with shapes (11,) (2,4) 

# PANDAS

Pandas - Python for data analysis 

### basic usage

In [47]:
# create columns - pandas series 
# create tables - pandas dataframes 
# import files 
# save files 

In [48]:
# functions and methods for data preview,
# data cleaning, transformation, summarization 
# exploratory data analysis, plotting etc.

In [49]:
# installation
# pip install pandas / conda install pandas 

In [50]:
import numpy as np
import pandas as pd

In [52]:
print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_is_numpy_dev', '_lib', '_libs', '_np_version_under1p18', '_testing', '_tslib', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'con

# create a pandas series 

In [53]:
s = pd.Series([2,3,4,5,np.nan,6,7])

In [54]:
print(s)

0    2.0
1    3.0
2    4.0
3    5.0
4    NaN
5    6.0
6    7.0
dtype: float64


# Dataframe

In [57]:
arr = np.floor(np.random.randn(6,4) * 10)
arr

array([[  2., -16.,  -2., -18.],
       [  0.,  11., -10.,  -1.],
       [ -5.,   6., -21., -13.],
       [-10.,   0.,   6.,   1.],
       [ -6.,  -6.,   6., -11.],
       [ 16.,  -8., -22., -12.]])

In [59]:
df = pd.DataFrame(arr)
df

0     1     2     3
0   2.0 -16.0  -2.0 -18.0
1   0.0  11.0 -10.0  -1.0
2  -5.0   6.0 -21.0 -13.0
3 -10.0   0.0   6.0   1.0
4  -6.0  -6.0   6.0 -11.0
5  16.0  -8.0 -22.0 -12.0

In [60]:
# update the dataframe with column headers 
# and indexs

In [61]:
# create a date range 
dates = pd.date_range("20220425", periods=6)
dates

DatetimeIndex(['2022-04-25', '2022-04-26', '2022-04-27', '2022-04-28',
               '2022-04-29', '2022-04-30'],
              dtype='datetime64[ns]', freq='D')

In [62]:
# new dataframe 

df1 = pd.DataFrame(arr, index=dates,
                   columns=['A','B','C','D'])

df1

A     B     C     D
2022-04-25   2.0 -16.0  -2.0 -18.0
2022-04-26   0.0  11.0 -10.0  -1.0
2022-04-27  -5.0   6.0 -21.0 -13.0
2022-04-28 -10.0   0.0   6.0   1.0
2022-04-29  -6.0  -6.0   6.0 -11.0
2022-04-30  16.0  -8.0 -22.0 -12.0

# Import survey data

### data was obtained from a survey administered via google forms 
### the result was downloaded in csv format

In [2]:
import numpy as np
import pandas as pd

In [3]:
pd.read_csv('./datasets/survey.csv')

Timestamp            First Name             Gender  \
0   2022/04/25 12:55:47 PM GMT+1               Samuel                Male   
1   2022/04/25 12:56:07 PM GMT+1                 Basit               Male   
2   2022/04/25 12:56:11 PM GMT+1               Ayomide               Male   
3   2022/04/25 12:56:21 PM GMT+1                Bolaji               Male   
4   2022/04/25 12:56:21 PM GMT+1           oluwagbenga               Male   
5   2022/04/25 12:56:22 PM GMT+1                  Mike               Male   
6   2022/04/25 12:56:33 PM GMT+1             CHIJIOKE                Male   
7   2022/04/25 12:56:42 PM GMT+1            Eze Odera                Male   
8   2022/04/25 12:56:46 PM GMT+1          Oluwaponmile             Female   
9   2022/04/25 12:56:47 PM GMT+1                 EBERE               Male   
10  2022/04/25 12:56:53 PM GMT+1               Ehinome               Male   
11  2022/04/25 12:57:07 PM GMT+1                Choppa  Prefer not to say   
12  2022/04/25 12:57:19 PM GMT+1             Chijioke                Male   
13  2022/04/25 12:57:39 PM GMT+1              Adetunji               Male   
14  2022/04/25 12:57:43 PM GMT+1                 Viche               Male   
15  2022/04/25 12:57:50 PM GMT+1               Awesome               Male   
16  2022/04/25 12:57:52 PM GMT+1  Muhammad Abdussamad                Male   
17  2022/04/25 12:58:26 PM GMT+1              Blessing             Female   
18  2022/04/25 12:58:49 PM GMT+1              Gabriel                Male   
19  2022/04/25 12:59:29 PM GMT+1              Omotayo              Female   
20  2022/04/25 12:59:31 PM GMT+1                 Usifo               Male   
21   2022/04/25 1:00:35 PM GMT+1                 Sodiq               Male   
22   2022/04/25 1:01:42 PM GMT+1               Maryann             Female   
23   2022/04/25 1:03:36 PM GMT+1              Matthew                Male   
24   2022/04/25 1:04:13 PM GMT+1               Ayomide               Male   
25   2022/04/25 1:08:46 PM GMT+1               OYENIYI               Male   
26   2022/04/25 1:24:06 PM GMT+1               Oladayo               Male   
27   2022/04/25 1:43:21 PM GMT+1                AJAYI                Male   
28   2022/04/25 3:47:21 PM GMT+1              Chibueze               Male   
29   2022/04/25 7:24:26 PM GMT+1                 ALLEN               Male   
30   2022/04/25 7:44:50 PM GMT+1              Shileola               Male   
31  2022/04/25 10:13:39 PM GMT+1              Olusegun               Male   

    Hair Color    Country            Occupation  
0        Black      Ghana              Jobless   
1        Black    Nigeria           Businessman  
2        Black   Nigeria               Student   
3        Black    Nigeria         Self Employee  
4        Black    nigeria               student  
5        Black   Nigerian            Freelancer  
6        Black    Nigeria       Data Scientist   
7        Black   Nigeria               Student   
8        Black    Nigeria          Data Analyst  
9        Black    Nigeria  Financial consultant  
10       Black    Nigeria    Petroleum Engineer  
11         NaN        Nig                    DA  
12       Black   Nigeria        Data Scientist   
13       Black    Nigeria               Student  
14       Black   Nigeria         Snooker player  
15  BlackBrown        UAR                   OAP  
16       Black   Nigeria                Student  
17       Black   Nigerian                  NYSC  
18       Black  American   Senior Data Analyst   
19       Brown   Nigeria                  ChefT  
20       Black    Nigeria                  Data  
21       Black    Nigeria           H.R Officer  
22       Brown   Nigeria          Data Analyst   
23       Black   Nigeria         Self Employed   
24       Black    Nigeria               Student  
25       Black   NIGERIA           DATA ANALYST  
26       Black    Nigeria          Data Analyst  
27       Black   Nigeria        Public servant   
28       Black    Nigeria      

In [10]:
survey = pd.read_csv('./datasets/survey.csv')

In [11]:
survey.head(3)

Timestamp First Name Gender Hair Color   Country  \
0  2022/04/25 12:55:47 PM GMT+1    Samuel    Male      Black     Ghana   
1  2022/04/25 12:56:07 PM GMT+1      Basit   Male      Black   Nigeria   
2  2022/04/25 12:56:11 PM GMT+1    Ayomide   Male      Black  Nigeria    

    Occupation  
0     Jobless   
1  Businessman  
2     Student

# import excel file

In [9]:
url = './datasets/Super+Store+Data.xlsx'

store_sales = pd.read_excel(url)

In [10]:
store_sales

Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156 2016-11-08 2016-11-11    Second Class   
1          2  CA-2016-152156 2016-11-08 2016-11-11    Second Class   
2          3  CA-2016-138688 2016-06-12 2016-06-16    Second Class   
3          4  US-2015-108966 2015-10-11 2015-10-18  Standard Class   
4          5  US-2015-108966 2015-10-11 2015-10-18  Standard Class   
...      ...             ...        ...        ...             ...   
9989    9990  CA-2014-110422 2014-01-21 2014-01-23    Second Class   
9990    9991  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9991    9992  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9992    9993  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class   

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson   
1       CG-12520       Claire Gute   Consumer  United States        Henderson   
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles   
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale   
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale   
...          ...               ...        ...            ...              ...   
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami   
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa   
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa   
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa   
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster   

      ... Postal Code  Region       Product ID         Category Sub-Category  \
0     ...       42420   South  FUR-BO-10001798        Furniture    Bookcases   
1     ...       42420   South  FUR-CH-10000454        Furniture       Chairs   
2     ...       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3     ...       33311   South  FUR-TA-10000577        Furniture       Tables   
4     ...       33311   South  OFF-ST-10000760  Office Supplies      Storage   
...   ...         ...     ...              ...              ...          ...   
9989  ...       33180   South  FUR-FU-10001889        Furniture  Furnishings   
9990  ...       92627    West  FUR-FU-10000747        Furniture  Furnishings   
9991  ...       92627    West  TEC-PH-10003645       Technology       Phones   
9992  ...       92627    West  OFF-PA-10004041  Office Supplies        Paper   
9993  ...       92683    West  OFF-AP-10002684  Office Supplies   Appliances   

                                           Product Name     Sales  Quantity  \
0                     Bush Somerset Collection Bookcase  261.9600         2   
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2     Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3         Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                        Eldon Fold 'N Roll Cart System   22.3680         2   
...                                                 ...       ...       ...   
9989                             Ultra Door Pull Handle   25.2480         3   
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.9600         2   
9991                              Aastra 57i VoIP phone  258.5760         2   
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.6000         4   
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.1600         2   

      Discount    Profit  
0         0.00   41.9136  
1         0.00  219.5820  
2         0.00    6.8714  
3         0.45 -383.0310  
4         0.20    2.5164  
...        ...       ...  
9989      0.20    4.1028  
9990      0.00   15.6332  
9991      0.20   19.3932  
9992      0.

# import a json file

In [11]:
url = './datasets/users.json'

df = pd.read_json(url)

df

id                      name          username                      email  \
0   1             Leanne Graham              Bret          Sincere@april.biz   
1   2              Ervin Howell         Antonette          Shanna@melissa.tv   
2   3          Clementine Bauch          Samantha         Nathan@yesenia.net   
3   4          Patricia Lebsack          Karianne  Julianne.OConner@kory.org   
4   5          Chelsey Dietrich            Kamren   Lucio_Hettinger@annie.ca   
5   6      Mrs. Dennis Schulist  Leopoldo_Corkery    Karley_Dach@jasper.info   
6   7           Kurtis Weissnat      Elwyn.Skiles     Telly.Hoeger@billy.biz   
7   8  Nicholas Runolfsdottir V     Maxime_Nienow       Sherwood@rosamond.me   
8   9           Glenna Reichert          Delphine    Chaim_McDermott@dana.io   
9  10        Clementina DuBuque    Moriah.Stanton     Rey.Padberg@karina.biz   

                                             address                  phone  \
0  {'street': 'Kulas Light', 'suite': 'Apt. 556',...  1-770-736-8031 x56442   
1  {'street': 'Victor Plains', 'suite': 'Suite 87...    010-692-6593 x09125   
2  {'street': 'Douglas Extension', 'suite': 'Suit...         1-463-123-4447   
3  {'street': 'Hoeger Mall', 'suite': 'Apt. 692',...      493-170-9623 x156   
4  {'street': 'Skiles Walks', 'suite': 'Suite 351...          (254)954-1289   
5  {'street': 'Norberto Crossing', 'suite': 'Apt....   1-477-935-8478 x6430   
6  {'street': 'Rex Trail', 'suite': 'Suite 280', ...           210.067.6132   
7  {'street': 'Ellsworth Summit', 'suite': 'Suite...      586.493.6943 x140   
8  {'street': 'Dayna Park', 'suite': 'Suite 449',...   (775)976-6794 x41206   
9  {'street': 'Kattie Turnpike', 'suite': 'Suite ...           024-648-3804   

         website                                            company  
0  hildegard.org  {'name': 'Romaguera-Crona', 'catchPhrase': 'Mu...  
1  anastasia.net  {'name': 'Deckow-Crist', 'catchPhrase': 'Proac...  
2    ramiro.info  {'name': 'Romaguera-Jacobson', 'catchPhrase': ...  
3       kale.biz  {'name': 'Robel-Corkery', 'catchPhrase': 'Mult...  
4   demarco.info  {'name': 'Keebler LLC', 'catchPhrase': 'User-c...  
5        ola.org  {'name': 'Considine-Lockman', 'catchPhrase': '...  
6       elvis.io  {'name': 'Johns Group', 'catchPhrase': 'Config...  
7   jacynthe.com  {'name': 'Abernathy Group', 'catchPhrase': 'Im...  
8     conrad.com  {'name': 'Yost and Sons', 'catchPhrase': 'Swit...  
9    ambrose.net  {'name': 'Hoeger LLC', 'catchPhrase': 'Central...

# import from a website

In [12]:
# using pandas, read_html or read_table

In [1]:
import pandas as pd 
url = 'https://en.wikipedia.org/wiki/Body_mass_index'

df = pd.read_html(url)

In [3]:
len(df) # 10 tables were extracted from the website

10

In [7]:
bmi = df[2]

In [8]:
bmi

Category BMI (kg/m2)[c] BMI Prime[c]
0    Underweight (Severe thinness)         < 16.0       < 0.64
1  Underweight (Moderate thinness)    16.0 – 16.9  0.64 – 0.67
2      Underweight (Mild thinness)    17.0 – 18.4  0.68 – 0.73
3                     Normal range    18.5 – 24.9  0.74 – 0.99
4           Overweight (Pre-obese)    25.0 – 29.9  1.00 – 1.19
5                  Obese (Class I)    30.0 – 34.9  1.20 – 1.39
6                 Obese (Class II)    35.0 – 39.9  1.40 – 1.59
7                Obese (Class III)         ≥ 40.0       ≥ 1.60

# Edit our survey file and save a new copy 

In [13]:
survey.shape

(32, 6)

In [14]:
survey.head()

Timestamp   First Name Gender Hair Color   Country  \
0  2022/04/25 12:55:47 PM GMT+1      Samuel    Male      Black     Ghana   
1  2022/04/25 12:56:07 PM GMT+1        Basit   Male      Black   Nigeria   
2  2022/04/25 12:56:11 PM GMT+1      Ayomide   Male      Black  Nigeria    
3  2022/04/25 12:56:21 PM GMT+1       Bolaji   Male      Black   Nigeria   
4  2022/04/25 12:56:21 PM GMT+1  oluwagbenga   Male      Black   nigeria   

      Occupation  
0       Jobless   
1    Businessman  
2       Student   
3  Self Employee  
4        student

In [15]:
survey.head(3)

Timestamp First Name Gender Hair Color   Country  \
0  2022/04/25 12:55:47 PM GMT+1    Samuel    Male      Black     Ghana   
1  2022/04/25 12:56:07 PM GMT+1      Basit   Male      Black   Nigeria   
2  2022/04/25 12:56:11 PM GMT+1    Ayomide   Male      Black  Nigeria    

    Occupation  
0     Jobless   
1  Businessman  
2     Student

In [16]:
# bottom rows

survey.tail()

Timestamp First Name Gender Hair Color   Country  \
27   2022/04/25 1:43:21 PM GMT+1     AJAYI    Male      Black  Nigeria    
28   2022/04/25 3:47:21 PM GMT+1   Chibueze   Male      Black   Nigeria   
29   2022/04/25 7:24:26 PM GMT+1      ALLEN   Male      Black   Nigeria   
30   2022/04/25 7:44:50 PM GMT+1   Shileola   Male      Black  Nigeria    
31  2022/04/25 10:13:39 PM GMT+1   Olusegun   Male      Black   Nigeria   

           Occupation  
27    Public servant   
28            Banking  
29  CONTENT DEVELOPER  
30       Data Analyst  
31           Teaching

In [20]:
survey.Gender.unique()

array(['Male', 'Female', 'Prefer not to say'], dtype=object)

In [21]:
survey.columns

Index(['Timestamp', 'First Name', 'Gender', 'Hair Color', 'Country',
       'Occupation'],
      dtype='object')

In [24]:
males = survey[survey.Gender == 'Male']

In [26]:
males.head(2)

Timestamp First Name Gender Hair Color  Country  \
0  2022/04/25 12:55:47 PM GMT+1    Samuel    Male      Black    Ghana   
1  2022/04/25 12:56:07 PM GMT+1      Basit   Male      Black  Nigeria   

    Occupation  
0     Jobless   
1  Businessman

In [27]:
# save the records for males 
males.to_csv('./datasets/survey_males.csv', index=False)

In [30]:
survey["Hair Color"].unique()

array(['Black', nan, 'BlackBrown', 'Brown'], dtype=object)

In [39]:
import numpy as np 
survey[survey["Hair Color"] != 'Black'] 
survey[survey["Hair Color"] != 'Brown']

Timestamp            First Name             Gender  \
0   2022/04/25 12:55:47 PM GMT+1               Samuel                Male   
1   2022/04/25 12:56:07 PM GMT+1                 Basit               Male   
2   2022/04/25 12:56:11 PM GMT+1               Ayomide               Male   
3   2022/04/25 12:56:21 PM GMT+1                Bolaji               Male   
4   2022/04/25 12:56:21 PM GMT+1           oluwagbenga               Male   
5   2022/04/25 12:56:22 PM GMT+1                  Mike               Male   
6   2022/04/25 12:56:33 PM GMT+1             CHIJIOKE                Male   
7   2022/04/25 12:56:42 PM GMT+1            Eze Odera                Male   
8   2022/04/25 12:56:46 PM GMT+1          Oluwaponmile             Female   
9   2022/04/25 12:56:47 PM GMT+1                 EBERE               Male   
10  2022/04/25 12:56:53 PM GMT+1               Ehinome               Male   
11  2022/04/25 12:57:07 PM GMT+1                Choppa  Prefer not to say   
12  2022/04/25 12:57:19 PM GMT+1             Chijioke                Male   
13  2022/04/25 12:57:39 PM GMT+1              Adetunji               Male   
14  2022/04/25 12:57:43 PM GMT+1                 Viche               Male   
15  2022/04/25 12:57:50 PM GMT+1               Awesome               Male   
16  2022/04/25 12:57:52 PM GMT+1  Muhammad Abdussamad                Male   
17  2022/04/25 12:58:26 PM GMT+1              Blessing             Female   
18  2022/04/25 12:58:49 PM GMT+1              Gabriel                Male   
20  2022/04/25 12:59:31 PM GMT+1                 Usifo               Male   
21   2022/04/25 1:00:35 PM GMT+1                 Sodiq               Male   
23   2022/04/25 1:03:36 PM GMT+1              Matthew                Male   
24   2022/04/25 1:04:13 PM GMT+1               Ayomide               Male   
25   2022/04/25 1:08:46 PM GMT+1               OYENIYI               Male   
26   2022/04/25 1:24:06 PM GMT+1               Oladayo               Male   
27   2022/04/25 1:43:21 PM GMT+1                AJAYI                Male   
28   2022/04/25 3:47:21 PM GMT+1              Chibueze               Male   
29   2022/04/25 7:24:26 PM GMT+1                 ALLEN               Male   
30   2022/04/25 7:44:50 PM GMT+1              Shileola               Male   
31  2022/04/25 10:13:39 PM GMT+1              Olusegun               Male   

    Hair Color    Country            Occupation  
0        Black      Ghana              Jobless   
1        Black    Nigeria           Businessman  
2        Black   Nigeria               Student   
3        Black    Nigeria         Self Employee  
4        Black    nigeria               student  
5        Black   Nigerian            Freelancer  
6        Black    Nigeria       Data Scientist   
7        Black   Nigeria               Student   
8        Black    Nigeria          Data Analyst  
9        Black    Nigeria  Financial consultant  
10       Black    Nigeria    Petroleum Engineer  
11         NaN        Nig                    DA  
12       Black   Nigeria        Data Scientist   
13       Black    Nigeria               Student  
14       Black   Nigeria         Snooker player  
15  BlackBrown        UAR                   OAP  
16       Black   Nigeria                Student  
17       Black   Nigerian                  NYSC  
18       Black  American   Senior Data Analyst   
20       Black    Nigeria                  Data  
21       Black    Nigeria           H.R Officer  
23       Black   Nigeria         Self Employed   
24       Black    Nigeria               Student  
25       Black   NIGERIA           DATA ANALYST  
26       Black    Nigeria          Data Analyst  
27       Black   Nigeria        Public servant   
28       Black    Nigeria               Banking  
29       Black    Nigeria     CONTENT DEVELOPER  
30       Black   Nigeria           Data Analyst  
31       Black    Nigeria              Teaching

In [35]:
survey

Timestamp            First Name             Gender  \
0   2022/04/25 12:55:47 PM GMT+1               Samuel                Male   
1   2022/04/25 12:56:07 PM GMT+1                 Basit               Male   
2   2022/04/25 12:56:11 PM GMT+1               Ayomide               Male   
3   2022/04/25 12:56:21 PM GMT+1                Bolaji               Male   
4   2022/04/25 12:56:21 PM GMT+1           oluwagbenga               Male   
5   2022/04/25 12:56:22 PM GMT+1                  Mike               Male   
6   2022/04/25 12:56:33 PM GMT+1             CHIJIOKE                Male   
7   2022/04/25 12:56:42 PM GMT+1            Eze Odera                Male   
8   2022/04/25 12:56:46 PM GMT+1          Oluwaponmile             Female   
9   2022/04/25 12:56:47 PM GMT+1                 EBERE               Male   
10  2022/04/25 12:56:53 PM GMT+1               Ehinome               Male   
11  2022/04/25 12:57:07 PM GMT+1                Choppa  Prefer not to say   
12  2022/04/25 12:57:19 PM GMT+1             Chijioke                Male   
13  2022/04/25 12:57:39 PM GMT+1              Adetunji               Male   
14  2022/04/25 12:57:43 PM GMT+1                 Viche               Male   
15  2022/04/25 12:57:50 PM GMT+1               Awesome               Male   
16  2022/04/25 12:57:52 PM GMT+1  Muhammad Abdussamad                Male   
17  2022/04/25 12:58:26 PM GMT+1              Blessing             Female   
18  2022/04/25 12:58:49 PM GMT+1              Gabriel                Male   
19  2022/04/25 12:59:29 PM GMT+1              Omotayo              Female   
20  2022/04/25 12:59:31 PM GMT+1                 Usifo               Male   
21   2022/04/25 1:00:35 PM GMT+1                 Sodiq               Male   
22   2022/04/25 1:01:42 PM GMT+1               Maryann             Female   
23   2022/04/25 1:03:36 PM GMT+1              Matthew                Male   
24   2022/04/25 1:04:13 PM GMT+1               Ayomide               Male   
25   2022/04/25 1:08:46 PM GMT+1               OYENIYI               Male   
26   2022/04/25 1:24:06 PM GMT+1               Oladayo               Male   
27   2022/04/25 1:43:21 PM GMT+1                AJAYI                Male   
28   2022/04/25 3:47:21 PM GMT+1              Chibueze               Male   
29   2022/04/25 7:24:26 PM GMT+1                 ALLEN               Male   
30   2022/04/25 7:44:50 PM GMT+1              Shileola               Male   
31  2022/04/25 10:13:39 PM GMT+1              Olusegun               Male   

    Hair Color    Country            Occupation  
0        Black      Ghana              Jobless   
1        Black    Nigeria           Businessman  
2        Black   Nigeria               Student   
3        Black    Nigeria         Self Employee  
4        Black    nigeria               student  
5        Black   Nigerian            Freelancer  
6        Black    Nigeria       Data Scientist   
7        Black   Nigeria               Student   
8        Black    Nigeria          Data Analyst  
9        Black    Nigeria  Financial consultant  
10       Black    Nigeria    Petroleum Engineer  
11         NaN        Nig                    DA  
12       Black   Nigeria        Data Scientist   
13       Black    Nigeria               Student  
14       Black   Nigeria         Snooker player  
15  BlackBrown        UAR                   OAP  
16       Black   Nigeria                Student  
17       Black   Nigerian                  NYSC  
18       Black  American   Senior Data Analyst   
19       Brown   Nigeria                  ChefT  
20       Black    Nigeria                  Data  
21       Black    Nigeria           H.R Officer  
22       Brown   Nigeria          Data Analyst   
23       Black   Nigeria         Self Employed   
24       Black    Nigeria               Student  
25       Black   NIGERIA           DATA ANALYST  
26       Black    Nigeria          Data Analyst  
27       Black   Nigeria        Public servant   
28       Black    Nigeria      

In [40]:
survey.dropna()

Timestamp            First Name  Gender  Hair Color  \
0   2022/04/25 12:55:47 PM GMT+1               Samuel     Male       Black   
1   2022/04/25 12:56:07 PM GMT+1                 Basit    Male       Black   
2   2022/04/25 12:56:11 PM GMT+1               Ayomide    Male       Black   
3   2022/04/25 12:56:21 PM GMT+1                Bolaji    Male       Black   
4   2022/04/25 12:56:21 PM GMT+1           oluwagbenga    Male       Black   
5   2022/04/25 12:56:22 PM GMT+1                  Mike    Male       Black   
6   2022/04/25 12:56:33 PM GMT+1             CHIJIOKE     Male       Black   
7   2022/04/25 12:56:42 PM GMT+1            Eze Odera     Male       Black   
8   2022/04/25 12:56:46 PM GMT+1          Oluwaponmile  Female       Black   
9   2022/04/25 12:56:47 PM GMT+1                 EBERE    Male       Black   
10  2022/04/25 12:56:53 PM GMT+1               Ehinome    Male       Black   
12  2022/04/25 12:57:19 PM GMT+1             Chijioke     Male       Black   
13  2022/04/25 12:57:39 PM GMT+1              Adetunji    Male       Black   
14  2022/04/25 12:57:43 PM GMT+1                 Viche    Male       Black   
15  2022/04/25 12:57:50 PM GMT+1               Awesome    Male  BlackBrown   
16  2022/04/25 12:57:52 PM GMT+1  Muhammad Abdussamad     Male       Black   
17  2022/04/25 12:58:26 PM GMT+1              Blessing  Female       Black   
18  2022/04/25 12:58:49 PM GMT+1              Gabriel     Male       Black   
19  2022/04/25 12:59:29 PM GMT+1              Omotayo   Female       Brown   
20  2022/04/25 12:59:31 PM GMT+1                 Usifo    Male       Black   
21   2022/04/25 1:00:35 PM GMT+1                 Sodiq    Male       Black   
22   2022/04/25 1:01:42 PM GMT+1               Maryann  Female       Brown   
23   2022/04/25 1:03:36 PM GMT+1              Matthew     Male       Black   
24   2022/04/25 1:04:13 PM GMT+1               Ayomide    Male       Black   
25   2022/04/25 1:08:46 PM GMT+1               OYENIYI    Male       Black   
26   2022/04/25 1:24:06 PM GMT+1               Oladayo    Male       Black   
27   2022/04/25 1:43:21 PM GMT+1                AJAYI     Male       Black   
28   2022/04/25 3:47:21 PM GMT+1              Chibueze    Male       Black   
29   2022/04/25 7:24:26 PM GMT+1                 ALLEN    Male       Black   
30   2022/04/25 7:44:50 PM GMT+1              Shileola    Male       Black   
31  2022/04/25 10:13:39 PM GMT+1              Olusegun    Male       Black   

      Country            Occupation  
0       Ghana              Jobless   
1     Nigeria           Businessman  
2    Nigeria               Student   
3     Nigeria         Self Employee  
4     nigeria               student  
5    Nigerian            Freelancer  
6     Nigeria       Data Scientist   
7    Nigeria               Student   
8     Nigeria          Data Analyst  
9     Nigeria  Financial consultant  
10    Nigeria    Petroleum Engineer  
12   Nigeria        Data Scientist   
13    Nigeria               Student  
14   Nigeria         Snooker player  
15        UAR                   OAP  
16   Nigeria                Student  
17   Nigerian                  NYSC  
18  American   Senior Data Analyst   
19   Nigeria                  ChefT  
20    Nigeria                  Data  
21    Nigeria           H.R Officer  
22   Nigeria          Data Analyst   
23   Nigeria         Self Employed   
24    Nigeria               Student  
25   NIGERIA           DATA ANALYST  
26    Nigeria          Data Analyst  
27   Nigeria        Public servant   
28    Nigeria               Banking  
29    Nigeria     CONTENT DEVELOPER  
30   Nigeria           Data Analyst  
31    Nigeria              Teaching

In [47]:
#  replace NAN with another value 

survey["Hair Color"].fillna("Not applicable", inplace=True)

In [49]:
survey.head(3)

Timestamp First Name Gender Hair Color   Country  \
0  2022/04/25 12:55:47 PM GMT+1    Samuel    Male      Black     Ghana   
1  2022/04/25 12:56:07 PM GMT+1      Basit   Male      Black   Nigeria   
2  2022/04/25 12:56:11 PM GMT+1    Ayomide   Male      Black  Nigeria    

    Occupation  
0     Jobless   
1  Businessman  
2     Student

In [61]:
survey['Age'] = ''

In [62]:
survey.columns

Index(['Timestamp', 'First Name', 'Gender', 'Hair Color', 'Country',
       'Occupation', 'Age'],
      dtype='object')

In [63]:
survey

Timestamp            First Name             Gender  \
0   2022/04/25 12:55:47 PM GMT+1               Samuel                Male   
1   2022/04/25 12:56:07 PM GMT+1                 Basit               Male   
2   2022/04/25 12:56:11 PM GMT+1               Ayomide               Male   
3   2022/04/25 12:56:21 PM GMT+1                Bolaji               Male   
4   2022/04/25 12:56:21 PM GMT+1           oluwagbenga               Male   
5   2022/04/25 12:56:22 PM GMT+1                  Mike               Male   
6   2022/04/25 12:56:33 PM GMT+1             CHIJIOKE                Male   
7   2022/04/25 12:56:42 PM GMT+1            Eze Odera                Male   
8   2022/04/25 12:56:46 PM GMT+1          Oluwaponmile             Female   
9   2022/04/25 12:56:47 PM GMT+1                 EBERE               Male   
10  2022/04/25 12:56:53 PM GMT+1               Ehinome               Male   
11  2022/04/25 12:57:07 PM GMT+1                Choppa  Prefer not to say   
12  2022/04/25 12:57:19 PM GMT+1             Chijioke                Male   
13  2022/04/25 12:57:39 PM GMT+1              Adetunji               Male   
14  2022/04/25 12:57:43 PM GMT+1                 Viche               Male   
15  2022/04/25 12:57:50 PM GMT+1               Awesome               Male   
16  2022/04/25 12:57:52 PM GMT+1  Muhammad Abdussamad                Male   
17  2022/04/25 12:58:26 PM GMT+1              Blessing             Female   
18  2022/04/25 12:58:49 PM GMT+1              Gabriel                Male   
19  2022/04/25 12:59:29 PM GMT+1              Omotayo              Female   
20  2022/04/25 12:59:31 PM GMT+1                 Usifo               Male   
21   2022/04/25 1:00:35 PM GMT+1                 Sodiq               Male   
22   2022/04/25 1:01:42 PM GMT+1               Maryann             Female   
23   2022/04/25 1:03:36 PM GMT+1              Matthew                Male   
24   2022/04/25 1:04:13 PM GMT+1               Ayomide               Male   
25   2022/04/25 1:08:46 PM GMT+1               OYENIYI               Male   
26   2022/04/25 1:24:06 PM GMT+1               Oladayo               Male   
27   2022/04/25 1:43:21 PM GMT+1                AJAYI                Male   
28   2022/04/25 3:47:21 PM GMT+1              Chibueze               Male   
29   2022/04/25 7:24:26 PM GMT+1                 ALLEN               Male   
30   2022/04/25 7:44:50 PM GMT+1              Shileola               Male   
31  2022/04/25 10:13:39 PM GMT+1              Olusegun               Male   

        Hair Color    Country            Occupation Age  
0            Black      Ghana              Jobless       
1            Black    Nigeria           Businessman      
2            Black   Nigeria               Student       
3            Black    Nigeria         Self Employee      
4            Black    nigeria               student      
5            Black   Nigerian            Freelancer      
6            Black    Nigeria       Data Scientist       
7            Black   Nigeria               Student       
8            Black    Nigeria          Data Analyst      
9            Black    Nigeria  Financial consultant      
10           Black    Nigeria    Petroleum Engineer      
11  Not applicable        Nig                    DA      
12           Black   Nigeria        Data Scientist       
13           Black    Nigeria               Student      
14           Black   Nigeria         Snooker player      
15      BlackBrown        UAR                   OAP      
16           Black   Nigeria                Student      
17           Black   Nigerian                  NYSC      
18           Black  American   Senior Data Analyst       
19           Brown   Nigeria                  ChefT      
20           Black    Nigeria                  Data      
21           Black    Nigeria           H.R Officer      
22           Brown   Nigeria          Data Analyst       
23           Black   Nigeria         Self Employed       
24           Black    Nigeria  